### ISSUE TITLE
Usage on FreeRTOS

### ISSUE THREAD

**Issue by Saiiijchan** [GorgonMeducer/perf_counter#35]
Dear Gorgon

I'm trying to use perf_counter on FreeRTOS for cortex-m33 but have questions about how to use it.

I have put `perfc_port_insert_to_system_timer_insert_ovf_handler` in `Systick_Handler` and compiled "perf_counter.c" and "perf_os_patch_freertos.c". I saw in the README that `__super_loop_monitor__`  is used to measure the usage of a thread in RTOS.

I have a demo as follows:
```
static void prvQueueSendTask( void *pvParameters )
{
    (void) pvParameters;
    int i = 0;
    init_task_cycle_counter();
    /* Delay 1000ms */
    TickType_t t = pdMS_TO_TICKS(1000);
    printf("1s ticks: %ld\n", t);
    uint32_t wTIck = xTaskGetTickCount();

    __super_loop_monitor__(5) {
        i++;
        printf("send, i = %u \n",i);
        delay_ms(500);
        xTaskDelayUntil( &wTIck, t );
    }
}
```

Systick parameters:
```
#define configCPU_CLOCK_HZ ((unsigned long)25000000)
#define configTICK_RATE_HZ ((TickType_t)1000)

void SystemCoreClockUpdate(void)
{
    SystemCoreClock = 25000000;
}

```

The output:
```
1s ticks: 1000
send, i = 1
send, i = 2
send, i = 3
send, i = 4
send, i = 5
prvQueueSendTask CPU Usage 100.000%

```

For expection, it should be 50% (Periodic is 1000ms and loop 500ms by delay_ms(500)) but the result is 100%。Is there something wrong with the way I use it?

Best regards.

**Comment by GorgonMeducer** [comment]
@Saiiijchan `delay_ms()` comes from perf_counter, a blocking code (that occupies CPU all the time); if you use the delay functions from FreeRTOS, you will see differences. 

> I have put perfc_port_insert_to_system_timer_insert_ovf_handler in Systick_Handler and compiled "perf_counter.c"

If you are using Arm Compiler 5 or Arm Compiler 6, you don't have to do so. Instead, you can use [systick_wrapper_ual.s](https://github.com/GorgonMeducer/perf_counter/blob/CMSIS-Pack/systick_wrapper_ual.s) for Arm Compiler 5 and [systick_wrapper_gnu.s](https://github.com/GorgonMeducer/perf_counter/blob/CMSIS-Pack/systick_wrapper_gnu.s) for Arm Compiler 6. 
Once you use these assembly files, you should **NOT** add `perfc_port_insert_to_system_timer_insert_ovf_handler` to `SysTick_Handler`. This is convenient when RTOS uses SysTick and provides the SysTick_Handler in assembly code. 

This is important, especially when RTOS occupies the SysTick. When RTOS occupies SysTick, you should initialize the perf_counter with:
```
init_cycle_counter(false);
```

I notice you are using `init_task_cycle_counter();` and `__super_loop_monitor__(5)`. To use them, for FreeRTOS, you have to deploy the [patch for FreeRTOS](https://github.com/GorgonMeducer/perf_counter/blob/CMSIS-Pack/os/perf_os_patch_freertos.c). Otherwise, those functions won't take the RTOS scheduling into consideration. 

For using the FreeRTOS patch (without cmsis-pack), you should create a header file (with any name you like) and put the following content:

```
//! \brief Enable RTOS Patch for perf_counter
#define __PERF_CNT_USE_RTOS__ 1
            
#define traceTASK_SWITCHED_OUT_DISABLE  
#define traceTASK_SWITCHED_IN_DISABLE

extern void __freertos_evr_on_task_switched_out (void *ptTCB);
extern void __freertos_evr_on_task_switched_in(void *ptTCB, unsigned int uxTopPriority) ;

#   define traceTASK_SWITCHED_OUT()                                             \
        __freertos_evr_on_task_switched_out(pxCurrentTCB)
#   define traceTASK_SWITCHED_IN()                                              \
        __freertos_evr_on_task_switched_in(pxCurrentTCB, uxTopReadyPriority)
```

And use `-include <your header file name>` for GCC, clang and arm compiler 6 to pre-include it before any compilation. 

I highly recommend you deploy perf_counter using cmsis-pack, which solves all the problems mentioned above. 

For more, please check the following blogs written in Chinese:

- [实时性迷思(5)——实战RTOS多任务性能分析](https://mp.weixin.qq.com/s?__biz=MzAxMzc2ODMzNg==&mid=2656103800&idx=1&sn=cccc780db0919c776cee4f438d545f3b&chksm=8039ce87b74e47911420345944ccd4a5485640fdd0407653c3da7615fe6898da320dfeb88125&token=130881136&lang=zh_CN#rd)

- [实时性迷(6)——如何进行跨任务性能分析](https://mp.weixin.qq.com/s?__biz=MzAxMzc2ODMzNg==&mid=2656103946&idx=1&sn=5f0e8692cdf2dcf01f4dc99ddf03ecb4&chksm=8039cdf5b74e44e308345d79372da241a5bd90baa88f4e8a5f5157aa547b692c52853083df3e&token=130881136&lang=zh_CN#rd)

**Comment by Saiiijchan** [comment]
Thanks for your suggestion and sorry for my late.

因为我是使用的 arm gcc，因为 init_cycle_counter() 有 __attribute__((constructor)) 修饰，所以在 FreerRTOS 下不需要再 init。
主要原因是你提到的这几个 macro 没有添加，导致 context switch 没有记录到 task tick cycle。对于 FreeRTOS 来说，这几个 macro 加到 FreeRTOSConfig.h 即可，目前测试都 OK，感谢你的帮助。
```
#define traceTASK_SWITCHED_OUT_DISABLE  
#define traceTASK_SWITCHED_IN_DISABLE

extern void __freertos_evr_on_task_switched_out (void *ptTCB);
extern void __freertos_evr_on_task_switched_in(void *ptTCB, unsigned int uxTopPriority) ;

#   define traceTASK_SWITCHED_OUT()                                             \
        __freertos_evr_on_task_switched_out(pxCurrentTCB)
#   define traceTASK_SWITCHED_IN()                                              \
        __freertos_evr_on_task_switched_in(pxCurrentTCB, uxTopReadyPriority)
```

在 Readme 中，这一段 [Read measurement result via `__usage__`](https://github.com/GorgonMeducer/perf_counter#:~:text=Read%20measurement%20result%20via%20__usage__)，printf 下面的位置似乎更符合预期。
```
void main(void)
{
    ...
    while (1) {
        
        float fUsage = 0.0f;
        __cpu_usage__(10, {
            fUsage = __usage__; /*< "__usage__" stores the result */
            printf("task 1 cpu usage %3.2f %%\r\n", (double)fUsage);
        }) {
            delay_us(30000);
        }

        delay_us(70000);
    }
    ...
}
```

另外我正在看 PMU 部分，关于 perf_port_pmu.c 中的 perfc_port_init_system_timer(）有一些疑问。
这个 function name 和 perf_port_default.c 中的一样。但是功能确是关闭  Systick 并 enable PMU，这个有点疑惑。另外为什么 enable PMU 情况下要关闭 SysTick，这两个不是可以共存的吗？

**Comment by GorgonMeducer** [comment]
> 因为我是使用的 arm gcc，因为 init_cycle_counter() 有 attribute((constructor)) 修饰，所以在 FreerRTOS 下不需要再 init。

`init_cycle_counter()` 可以多次调用，问题不大。关键是`init_cycle_counter()`会根据`SystemCoreClock`的值对物理时间和cpu cycle counter之间的比例进行更新——如果你的系统是在进入main()以后才更新系统频率，或者你不确定 `init_cycle_counter()`作为constructor被调用**之后**系统频率是否更新过，还是推荐在 `main()` 函数里再初始化一次，具体请根据你的实际情况来把握。


> 这个 function name 和 perf_port_default.c 中的一样。

perf_port_default.c 中的函数都是 `__WEAK` 的，当 perf_port_pmu.c 和 perf_port_default.c 同时存在时，后者中的函数会取代 `__WEAK` 版本的函数。也就是说，这里不会出现你说的使用PMU却关闭SysTick的情况。

> 在 Readme 中，这一段 [Read measurement result via __usage__](https://github.com/GorgonMeducer/perf_counter#:~:text=Read%20measurement%20result%20via%20__usage__)，printf 下面的位置似乎更符合预期。

这段代码的本意是展示如何通过 `__usage__` 来读取结果到 `__cpu_usage__` 的外部来使用，所以才会把printf()放到外面去，你的建议也挺好，所以我在的developing分支里已经按照你的建议更新了。非常感谢反馈。

最后，想必你已经知道 `__cpu_usage__()` 和 `__super_loop_monitor__()` 的区别了吧。

**Comment by Saiiijchan** [comment]
```init_cycle_counter()``` 我会再仔细检查 boot 过程中的 SystemCoreClock 和 rtos scheduler startup 时候 sys frequence 是否有变化，感谢提醒。

关于 ``` __cpu_usage__() ``` 和 ``` __super_loop_monitor__() ```，在拜读你的 Blog 后并结合 source code，我的理解是 ``` __super_loop_monitor__() ``` 就是专门计算 rtos task cycle 的，在每次 context switch 时候将 cycle usage 记录在 task stack 里，避免了 [你不考虑高优先级任务、中断之类在执行循环体的时候发生抢占么？抢占后的CPU周期数也要从测量结果中扣除啊！](https://mp.weixin.qq.com/s?__biz=MzAxMzc2ODMzNg==&mid=2656103800&idx=1&sn=cccc780db0919c776cee4f438d545f3b&chksm=8039ce87b74e47911420345944ccd4a5485640fdd0407653c3da7615fe6898da320dfeb88125&token=130881136&lang=zh_CN#rd:~:text=%E4%BD%A0%E4%B8%8D%E8%80%83%E8%99%91%E9%AB%98%E4%BC%98%E5%85%88%E7%BA%A7%E4%BB%BB%E5%8A%A1%E3%80%81%E4%B8%AD%E6%96%AD%E4%B9%8B%E7%B1%BB%E5%9C%A8%E6%89%A7%E8%A1%8C%E5%BE%AA%E7%8E%AF%E4%BD%93%E7%9A%84%E6%97%B6%E5%80%99%E5%8F%91%E7%94%9F%E6%8A%A2%E5%8D%A0%E4%B9%88%EF%BC%9F%E6%8A%A2%E5%8D%A0%E5%90%8E%E7%9A%84CPU%E5%91%A8%E6%9C%9F%E6%95%B0%E4%B9%9F%E8%A6%81%E4%BB%8E%E6%B5%8B%E9%87%8F%E7%BB%93%E6%9E%9C%E4%B8%AD%E6%89%A3%E9%99%A4%E5%95%8A%EF%BC%81) preempt issues。``` __cpu_usage__() ``` 感觉就更 general 或是说适用 single thread。此外关于预编译的文章也十分有帮助，受益良多！


> perf_port_default.c 中的函数都是 `__WEAK` 的，当 perf_port_pmu.c 和 perf_port_default.c 同时存在时，后者中的函数会取代 `__WEAK` 版本的函数。也就是说，这里不会出现你说的使用PMU却关闭SysTick的情况。


抱歉这个我之前没有仔细看 code，在有 PMU 情况下，相关的 tick cycle number 是直接从 pmu cycle counter 读取而不是 Systick->Val，所以 baremetal 时候另外 enable systick 即可。

**Comment by GorgonMeducer** [comment]
另外，需要特别强调的是：中断处理程序本质上也是一种凌驾于普通任务优先级之上的任务，如果RTOS的调度没有覆盖全部或者某些中断处理程序，那么它们的运行时间在使用 `__super_loop_monitor__()` 就没法被扣除了。

**Comment by Saiiijchan** [comment]
谢谢提醒，ISR 的时间会被计算进 task 里这个似乎是无法避免的，FreeRTOS kernel 的 run time status 也无法消除 ISR
 的影响。减少这方面影响只能从 app 方面来做，尽量缩短 ISR 的处理事件来保证 task usage 的准确性。

**Comment by GorgonMeducer** [comment]
有一些RTOS会要求用户在所有ISR的入口和出口处调用一些RTOS提供的语法糖来实现对ISR的接管——这类情况下ISR也有可能被作为任务的一种来接管。如果我没有记错，RT-Thread好像就是这样。

貌似所有问题都解决了。不介意的话，我先close这个issue。如果还有相关讨论，您可以重新打开。
如果有新的问题，欢迎起一个新的issue。
